# Generated by Django 4.2.6 on 2023-11-03 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductService', '0006_remove_productinventory_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_inventory',
            new_name='stock_quantity',
        ),
    ]
