# Generated by Django 4.2.6 on 2023-11-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductService', '0009_remove_product_product_inventory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='user',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='ProductInventory',
        ),
    ]
