# Generated by Django 4.2.6 on 2023-11-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductService', '0012_productreview_review_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='user_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
