# Generated by Django 4.2.7 on 2023-11-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductService', '0013_alter_productreview_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='review_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
